import localFont from "next/font/local";
import "./globals.css";
import Header from "@/app/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        <div className="flex flex-col items-center justify-center min-h-screen w-full px-4">
          <Header />
          <main className="flex flex-col items-center justify-center w-full max-w-4xl">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
